export const bandeiraOptions = [
  { value: "Visa", label: "Visa", imgSrc: "/bandeiras/visa.svg" },
  { value: "Mastercard", label: "Mastercard", imgSrc: "/bandeiras/mastercard.svg" },
  { value: "Amex", label: "Amex", imgSrc: "/bandeiras/amex.svg" },
  { value: "Elo", label: "Elo", imgSrc: "/bandeiras/elo.svg" },
  { value: "Hipercard", label: "Hipercard", imgSrc: "/bandeiras/hipercard.svg" },
];

export const empresaOptions = [
  { value: "99Pay", label: "99Pay", imgSrc: "/contas/99Pay.png" },
  { value: "Agibank", label: "Agibank", imgSrc: "/contas/agibank.png" },
  { value: "Alelo", label: "Alelo", imgSrc: "/contas/alelo.png" },
  { value: "Amex", label: "Amex", imgSrc: "/contas/amex.png" },
  { value: "Banestes", label: "Banestes", imgSrc: "/contas/banestes.png" },
  { value: "Banrisul", label: "Banrisul", imgSrc: "/contas/banrisul.png" },
  { value: "Bari", label: "Bari", imgSrc: "/contas/bari.png" },
  { value: "BB", label: "BB", imgSrc: "/contas/bb.png" },
  { value: "BMG", label: "BMG", imgSrc: "/contas/bmg.png" },
  { value: "Banco BMG Corinthians", label: "Banco BMG Corinthians", imgSrc: "/contas/bmg-corinthians.png" },
  { value: "Bradesco", label: "Bradesco", imgSrc: "/contas/bradesco.png" },
  { value: "Caixa", label: "Caixa", imgSrc: "/contas/caixa.png" },
  { value: "C6bank", label: "C6bank", imgSrc: "/contas/c6bank.png" },
  { value: "Credicard", label: "Credicard", imgSrc: "/contas/credicard.png" },
  { value: "Digio", label: "Digio", imgSrc: "/contas/digio.png" },
  { value: "Elo", label: "Elo", imgSrc: "/contas/elo.png" },
  { value: "Intermedium", label: "Intermedium", imgSrc: "/contas/intermedium.png" },
  { value: "Neon", label: "Neon", imgSrc: "/contas/neon.png" },
  { value: "Neon Pagamentos", label: "Neon Pagamentos", imgSrc: "/contas/neon.png" },
  { value: "Nubank", label: "Nubank", imgSrc: "/contas/nubank.png" },
  { value: "Nubank PJ", label: "Nubank PJ", imgSrc: "/contas/nubank.pj.png" },
  { value: "Nu-Invest", label: "Nu-Invest", imgSrc: "/contas/nu-invest.png" },
  { value: "Original", label: "Original", imgSrc: "/contas/original.png" },
  { value: "Banco Original", label: "Banco Original", imgSrc: "/contas/original.png" },
  { value: "Pan", label: "Pan", imgSrc: "/contas/pan.png" },
  { value: "Banco Pan", label: "Banco Pan", imgSrc: "/contas/pan.png" },
  { value: "PicPay", label: "PicPay", imgSrc: "/contas/picpay.png" },
  { value: "PagSeguro", label: "PagSeguro", imgSrc: "/contas/pagseguro.png" },
  { value: "PagBank", label: "PagBank", imgSrc: "/contas/pagbank.png" },
  { value: "Pagar-me", label: "Pagar-me", imgSrc: "/contas/pagar-me.png" },
  { value: "RecargaPay", label: "RecargaPay", imgSrc: "/contas/recargapay.png" },
  { value: "MercadoPago", label: "MercadoPago", imgSrc: "/contas/mercadopago.png" },
  { value: "PayPal", label: "PayPal", imgSrc: "/contas/paypal.png" },
  { value: "Pix", label: "Pix", imgSrc: "/contas/pix.png" },
  { value: "Itau", label: "Itau", imgSrc: "/contas/itau.png" },
  { value: "Itau Personnalité", label: "Itau Personnalité", imgSrc: "/contas/itaupersonnalite.png" },
  { value: "Itau Uniclass", label: "Itau Uniclass", imgSrc: "/contas/itau-uniclass.png" },
  { value: "Itau Ion", label: "Itau Ion", imgSrc: "/contas/itau-ion.png" },
  { value: "Banco do Nordeste", label: "Banco do Nordeste", imgSrc: "/contas/nordeste.png" },
  { value: "Sicoob", label: "Sicoob", imgSrc: "/contas/sicoob.png" },
  { value: "Sicredi", label: "Sicredi", imgSrc: "/contas/sicredi.png" },
  { value: "XP", label: "XP", imgSrc: "/contas/xp.png" },
  { value: "Ebanx", label: "Ebanx", imgSrc: "/contas/ebanxgo.png" },
  { value: "Mais", label: "Mais", imgSrc: "/contas/mais.png" },
  { value: "Moey", label: "Moey", imgSrc: "/contas/moey.png" },
  { value: "Cora", label: "Cora", imgSrc: "/contas/cora.png" },
  { value: "Stone", label: "Stone", imgSrc: "/contas/stone.png" },
  { value: "SumUp", label: "SumUp", imgSrc: "/contas/sumup.png" },
  { value: "Sodexo", label: "Sodexo", imgSrc: "/contas/sodexo.png" },
  { value: "Ticket", label: "Ticket", imgSrc: "/contas/ticket.png" },
  { value: "Up.Brasil", label: "Up.Brasil", imgSrc: "/contas/up.brasil.png" }
];