import {
  FaCar,
  FaMoneyBill,
  FaUtensils,
  FaShoppingCart,
  FaHome,
  FaBolt,
  FaBus,
  FaTrain,
  FaPlane,
  FaMotorcycle,
  FaBicycle,
  FaTshirt,
  FaGift,
  FaPhoneAlt,
  FaAppleAlt,
  FaBeer,
  FaBook,
  FaHeart,
  FaDog,
  FaCat,
  FaGamepad,
  FaPiggyBank,
  FaRegSmile,
  FaTools,
  FaLaptop,
  FaRegCreditCard,
  FaShoppingBag,
  FaWineGlassAlt,
  FaBriefcase,
  FaUserShield,
  FaWallet,
  FaFirstAid,
  FaFileInvoiceDollar,
  FaParking
} from "react-icons/fa";

import {
  MdHomeRepairService,
  MdLocalHospital,
  MdSchool,
  MdWork,
  MdPets,
  MdFastfood,
  MdRestaurant,
  MdLocalGroceryStore,
} from "react-icons/md";

export const iconOptions = [
  { name: "FaCar", component: FaCar },
  { name: "FaMoneyBill", component: FaMoneyBill },
  { name: "FaUtensils", component: FaUtensils },
  { name: "FaShoppingCart", component: FaShoppingCart },
  { name: "FaHome", component: FaHome },
  { name: "FaBolt", component: FaBolt },
  { name: "FaBus", component: FaBus },
  { name: "FaTrain", component: FaTrain },
  { name: "FaPlane", component: FaPlane },
  { name: "FaMotorcycle", component: FaMotorcycle },
  { name: "FaBicycle", component: FaBicycle },
  { name: "FaTshirt", component: FaTshirt },
  { name: "FaGift", component: FaGift },
  { name: "FaPhoneAlt", component: FaPhoneAlt },
  { name: "FaAppleAlt", component: FaAppleAlt },
  { name: "FaBeer", component: FaBeer },
  { name: "FaBook", component: FaBook },
  { name: "FaHeart", component: FaHeart },
  { name: "FaDog", component: FaDog },
  { name: "FaCat", component: FaCat },
  { name: "FaGamepad", component: FaGamepad },
  { name: "FaPiggyBank", component: FaPiggyBank },
  { name: "FaRegSmile", component: FaRegSmile },
  { name: "FaTools", component: FaTools },
  { name: "FaLaptop", component: FaLaptop },
  { name: "FaRegCreditCard", component: FaRegCreditCard },
  { name: "FaShoppingBag", component: FaShoppingBag },
  { name: "FaWineGlassAlt", component: FaWineGlassAlt },
  { name: "FaBriefcase", component: FaBriefcase },
  { name: "FaUserShield", component: FaUserShield },
  { name: "FaWallet", component: FaWallet },
  { name: "FaFirstAid", component: FaFirstAid },
  { name: "FaFileInvoiceDollar", component: FaFileInvoiceDollar },
  { name: "FaParking", component: FaParking },

  // ícones do Material
  { name: "MdFastfood", component: MdFastfood },
  { name: "MdRestaurant", component: MdRestaurant },
  { name: "MdLocalGroceryStore", component: MdLocalGroceryStore },
  { name: "MdWork", component: MdWork },
  { name: "MdSchool", component: MdSchool },
  { name: "MdLocalHospital", component: MdLocalHospital },
  { name: "MdHomeRepairService", component: MdHomeRepairService },
  { name: "MdPets", component: MdPets },
];